### ISSUE TITLE
Higher Resolution Images

### ISSUE THREAD

**Issue by neur0manc** [james4k/gopher#3]
Hi @james4k 

I really like the wallpaper, find the [golang.org](https://golang.org) website reflection very cool. I tried to render this in blender to get some higher resolution versions off of it, but I have zero experience with blender, and sadly failed.

Would you be able to create a version in 3840×2160 pixels (aka UltraHD)?

I think it would make sense to host the files here in github, since the source is here already.

Would be really appreciated! Oh and thanks anyway for the image.

**Comment by james4k** [comment]
Just rendered out a few higher resolution versions.

Glad you enjoy the wallpaper. :)

https://github.com/james4k/gopher/releases/tag/v1.0

**Comment by ls42** [comment]
Just saw that the release is of 2014, sorry for missing it. Thanks again!
